# Site settings
title: Haonan Dong's Website
description: >
 Home page for Haonan Dong's Website.
author: Haonan Dong 
email: august_dong@163.com// haonandong.cn@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexcarpenter.github.io" # the base hostname & protocol for your site
github_username:  haonan-dong

# Build settings
#include:
source: _source
dstination: _deploy
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
