# Site settings
title: Haonan Dong's Website
emial: august_dong@163.com
description: Home page for Haonan Dong's Website.
url: "http://haonan-dong.github.io" # the base hostname & protocol for your site
github_username:  haonan-dong

# Build settings
#include:
#source: _source
#dstination: _deploy
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
