#o Site settings
title: Haonan Dong's Website 
email: august_dong@163.com haonandong.cn@gmail.cn
description: > # this means to ignore newlines until "baseurl:"
  This Website is under constrution and thanks for your visiting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://haonan-dong.github.io" # the base hostname & protocol for your site
github_username:  haonan-dong

# Build settings
markdown: kramdown
